CC = clang
CFLAGS = -Wextra -lm --pedantic -std=c11

all: zadanie1 zadanie2 zadanie3 zadanie4 zadanie5

zadanie1: zadanie1.c
    $(CC) $(CFLAGS) -o zadanie1 zadanie1.c

zadanie2: zadanie2.c
    $(CC) $(CFLAGS) -o zadanie2 zadanie2.c

zadanie3: zadanie3.c
    $(CC) $(CFLAGS) -o zadanie3 zadanie3.c

zadanie4: zadanie4.c
    $(CC) $(CFLAGS) -o zadanie4 zadanie4.c

zadanie5: zadanie5.c
    $(CC) $(CFLAGS) -o zadanie5 zadanie5.c

clean:
    rm -f zadanie1 zadanie2 zadanie3 zadanie4 zadanie5
