package app.generator;

import app.model.IFigure;
import app.model.MyCircle;
import app.model.MyTriangle;
import javafx.scene.paint.Color;

/**
 * A class that generates triangles based on a set of points.
 */
public class TriangleGenerator implements ShapeGenerator {

    /**
     * Gets the type of shape generated by this generator.
     *
     * @return The shape type, which is "Triangle".
     */
    @Override
    public String getShapeType() {
        return "Triangle";
    }

    /**
     * Checks if the generator is ready to create a shape.
     *
     * @return True if the generator has at least 3 points, false otherwise.
     */
    @Override
    public boolean isReady() {
        return points.size() > 2;
    }

    /**
     * Creates a triangle shape based on the points provided.
     *
     * @return A new instance of the MyTriangle class, initialized with the points.
     */
    @Override
    public IFigure createShape() {
        return new MyTriangle(points.get(0).getX(),
                points.get(1).getX(),
                points.get(2).getX(),
                points.get(0).getY(),
                points.get(1).getY(),
                points.get(2).getY());
    }

    /**
     * Returns a ghost shape of type IFigure based on the given coordinates.
     * If the number of points is equal to 2, a MyTriangle object is created with the given coordinates.
     * If the number of points is equal to 1, a MyTriangle object is created with the given coordinates.
     * If the number of points is not equal to 1, a MyCircle object is created with an example radius of 3.
     * The color of the ghost shape is set to "#000000aa".
     *
     * @param x the x-coordinate of the ghost shape
     * @param y the y-coordinate of the ghost shape
     * @return a ghost shape of type IFigure
     */
    @Override
    public final IFigure ghostShape(double x, double y) {
        if (points.size() == 2) {
            MyTriangle ghost = new MyTriangle(points.get(0).getX(),
                    points.get(1).getX(),
                    x,
                    points.get(0).getY(),
                    points.get(1).getY(),
                    y);
            ghost.setColor("#000000aa");
            return ghost;
        } else if (points.size() == 1) {
            MyTriangle ghost = new MyTriangle(points.get(0).getX(),
                    x,
                    x,
                    points.get(0).getY(),
                    y,
                    y);
            ghost.setStroke(Color.rgb(0, 0, 0, 0.5));
            ghost.setStrokeWidth(2);
            ghost.setColor("#000000aa");
            return ghost;
        } else {
            MyCircle ghost = new MyCircle(x, y, 3);
            ghost.setColor("#000000aa");
            return ghost;
        }
    }
}
