name: PDFlatex to Github Pages

on:
  push:
    branches:
      - workflow
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:edge

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build all .tex files
        run: |
          mkdir -p output
          OUTPUT_DIR=$(realpath output)

          for file in $(find . -name "*.tex"); do
              jobname=$(echo "${file%.tex}" | sed 's|^\./||; s|/|-|g')
              dir=$(dirname "$file")
              base=$(basename "$file")
              (
                  cd "$dir" || exit
                  echo "Compiling $file..."
                  pdflatex -interaction=nonstopmode -halt-on-error -shell-escape \
                      -output-directory "$OUTPUT_DIR" \
                      -jobname="$jobname" \
                      "$base" > /dev/null 2>&1
              )
          done

          find output -type f -regex '.*\.\(aux\|log\|out\|toc\|nav\|snm\|pyg\)$' -delete
          ls output
      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
